// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG-L-YJLsoMbBZA0F5LqdENKFiBDYtoHg',
    appId: '1:296991763291:web:1ed6086b8891667b83c87e',
    messagingSenderId: '296991763291',
    projectId: 'flutter-ecommerce-d1f89',
    authDomain: 'flutter-ecommerce-d1f89.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-d1f89.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBizUc0r_8djofv5XE0_N5G4lsS4QCB1pg',
    appId: '1:296991763291:android:6f6ad3b539dfcad183c87e',
    messagingSenderId: '296991763291',
    projectId: 'flutter-ecommerce-d1f89',
    storageBucket: 'flutter-ecommerce-d1f89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVvCg-gpQz3ITljNcB0kkI_MtfQEl7yO4',
    appId: '1:296991763291:ios:48eca54c04cde3a683c87e',
    messagingSenderId: '296991763291',
    projectId: 'flutter-ecommerce-d1f89',
    storageBucket: 'flutter-ecommerce-d1f89.appspot.com',
    iosClientId: '296991763291-irhr9o632pch9ujr1q4o3m764qtulk1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVvCg-gpQz3ITljNcB0kkI_MtfQEl7yO4',
    appId: '1:296991763291:ios:b8d2c867af4edb8483c87e',
    messagingSenderId: '296991763291',
    projectId: 'flutter-ecommerce-d1f89',
    storageBucket: 'flutter-ecommerce-d1f89.appspot.com',
    iosClientId: '296991763291-7ognm5r97o9sm1cs8adjim0mehufbgsn.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceFlutter.RunnerTests',
  );
}
